[package]
name = "game-note"
version = "0.1.0"
description = "A lightweight match-video review application"
authors = ["Hangzhou Amuswen Network Technology Co., Ltd."]
edition = "2021"
license = "MIT"
repository = "https://github.com/EmiranKaisar/MatchVideoPlayer"

[lib]
name = "game_note_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
http = "1"
http-range = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"

[profile.release]
panic = "abort"
strip = true
